#!/usr/bin/env node
/**
 * jules-queue-dispatcher.mjs
 * Next-Gen Jules Queue Dispatcher & Spec Enricher.
 *
 * Reads pending task specs from the vault queue, enriches prompts with the
 * Graphify codebase dependency subgraph, dispatches to the Jules API,
 * tracks state + daily rate limits, and archives processed specs.
 *
 * Orchestrated by VANTAGE co-pilot on Cato.
 *
 * STRICT ARCHITECT PR APPROVAL POLICY:
 *   - Jules sessions may open Pull Requests, but PRs must NEVER be
 *     auto-merged into `main`. Every PR is recorded in state as
 *     `AWAITING_ARCHITECT_APPROVAL` and requires Ben's manual review
 *     & approval on GitHub before merging.
 *
 * Usage:
 *   node jules-queue-dispatcher.mjs [--dry-run] [--limit N] [--verbose]
 *   node jules-queue-dispatcher.mjs --digest [--send]
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, renameSync, statSync } from 'fs';
import { join, basename } from 'path';
import { createSession, listSources } from './jules-client.mjs';
import { sendDiscordAlert } from './jules-discord.mjs';

// ==========================================
// Configuration
// ==========================================
const WORKSPACE = '/home/node/.openclaw/workspace';
const QUEUE_DIR = join(WORKSPACE, 'vault/01-ACTIVE/jules-queue');
const PROCESSED_DIR = join(QUEUE_DIR, 'processed');
const STATE_PATH = join(WORKSPACE, 'jules-state.json');
const GRAPH_PATH = '/home/node/.graphify/global-graph.json';

const DAILY_HARD_LIMIT = 100; // Google's hard cap
const MANUAL_RESERVE_BUFFER = 20; // Reserved strictly for Ben's manual on-demand sessions
const DAILY_SAFETY_LIMIT = DAILY_HARD_LIMIT - MANUAL_RESERVE_BUFFER; // 80 automated background cap
const HISTORY_CAP = 200; // Max dispatch history entries retained in state
const STATE_SCHEMA_VERSION = 2;

// ==========================================
// Strict Architect PR Approval Policy
// ==========================================
// Jules opens PRs via AUTO_CREATE_PR, but merging is ALWAYS manual.
// There is intentionally no merge/automerge code path anywhere in the
// Jules pipeline. This flag exists as a hard circuit breaker: it must
// never be set to true.
const PR_AUTO_MERGE_ENABLED = false;
const PR_STATUS_AWAITING = 'AWAITING_ARCHITECT_APPROVAL';

/**
 * Circuit breaker: abort the process if anything ever attempts to
 * enable PR auto-merge. PRs generated by Jules require Ben's manual
 * review & approval before merging — no exceptions.
 */
function assertNoAutoMerge() {
  if (PR_AUTO_MERGE_ENABLED !== false) {
    throw new Error('POLICY VIOLATION: Jules PR auto-merge is permanently disabled by the Strict Architect PR Approval Policy.');
  }
}

const args = process.argv.slice(2);
const DRY_RUN = args.includes('--dry-run');
const VERBOSE = args.includes('--verbose');
const DIGEST_MODE = args.includes('--digest');
const DIGEST_SEND = args.includes('--send');
const LIMIT_IDX = args.indexOf('--limit');
const RUN_LIMIT = LIMIT_IDX !== -1 ? parseInt(args[LIMIT_IDX + 1], 10) : Infinity;

// ==========================================
// Structured Logging
// ==========================================
function log(level, msg, data) {
  const ts = new Date().toISOString();
  const line = `[${ts}] [${level.toUpperCase()}] [JulesDispatcher] ${msg}`;
  if (data !== undefined) {
    console.log(line, typeof data === 'string' ? data : JSON.stringify(data));
  } else {
    console.log(line);
  }
}

// ==========================================
// Helpers
// ==========================================

/** Current date in America/Chicago (YYYY-MM-DD) for the daily counter. */
function chicagoToday() {
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: 'America/Chicago',
    year: 'numeric', month: '2-digit', day: '2-digit'
  }).format(new Date());
}

/**
 * Minimal frontmatter / header metadata parser (zero-dependency).
 * Supports:
 *   ---
 *   repo_path: ez-boat-numbers
 *   title: Fix the thing
 *   priority: high
 *   ---
 * or bare `key: value` lines in the first ~30 lines of the file.
 */
function parseSpecMetadata(raw) {
  const meta = {};
  const lines = raw.split('\n');

  // YAML-style frontmatter block
  if (lines[0] && lines[0].trim() === '---') {
    for (let i = 1; i < lines.length; i++) {
      const l = lines[i].trim();
      if (l === '---') break;
      const m = l.match(/^([A-Za-z0-9_\-]+)\s*:\s*(.+)$/);
      if (m) meta[m[1].toLowerCase().trim()] = m[2].trim().replace(/^["']|["']$/g, '');
    }
  } else {
    // Bare header metadata scan (first 30 non-body lines)
    for (let i = 0; i < Math.min(lines.length, 30); i++) {
      const l = lines[i].trim();
      if (l.startsWith('#')) {
        // Treat first H1 as title fallback
        if (!meta.title) meta.title = l.replace(/^#+\s*/, '').trim();
        continue;
      }
      const m = l.match(/^([A-Za-z0-9_\-]+)\s*:\s*(.+)$/);
      if (m && ['repo_path', 'repo', 'title', 'priority', 'branch', 'startingbranch'].includes(m[1].toLowerCase())) {
        meta[m[1].toLowerCase().trim()] = m[2].trim().replace(/^["']|["']$/g, '');
      }
    }
  }

  if (meta.repo && !meta.repo_path) meta.repo_path = meta.repo;
  if (meta.startingbranch && !meta.branch) meta.branch = meta.startingbranch;
  return meta;
}

/** Strip the frontmatter block (and bare header metadata) so the prompt is clean. */
function stripFrontmatter(raw) {
  const lines = raw.split('\n');
  if (lines[0] && lines[0].trim() === '---') {
    for (let i = 1; i < lines.length; i++) {
      if (lines[i].trim() === '---') return lines.slice(i + 1).join('\n').trim();
    }
  }
  // Bare header form: drop `key: value` metadata lines and keep prose/headings
  return lines
    .filter(l => {
      const m = l.trim().match(/^([A-Za-z0-9_\-]+)\s*:\s*(.+)$/);
      return !(m && ['repo_path', 'repo', 'title', 'priority', 'branch', 'startingbranch'].includes(m[1].toLowerCase()));
    })
    .join('\n')
    .trim();
}

/** Priority rank for sorting (lower = sooner). */
function priorityRank(p) {
  const v = (p || 'medium').toLowerCase();
  if (v === 'critical' || v === 'urgent' || v === 'p0') return 0;
  if (v === 'high' || v === 'p1') return 1;
  if (v === 'medium' || v === 'normal' || v === 'p2') return 2;
  if (v === 'low' || v === 'p3') return 3;
  const n = parseInt(v, 10);
  return Number.isNaN(n) ? 2 : n;
}

// ==========================================
// Graphify Context Enrichment
// ==========================================

/**
 * Load the Graphify global graph and extract the dependency subgraph for a repo.
 * Handles flexible node shapes: { id|path|file, repo, ... } and edges
 * as { edges: [...] } or { relationships: [...] } with source/target/from/to.
 */
function buildGraphifyBlock(repoPath) {
  const candidates = [
    GRAPH_PATH,
    join(WORKSPACE, repoPath, 'graphify-out/.graphify_analysis.json'),
    join(WORKSPACE, 'sovereign-cut-co/graphify-out/.graphify_analysis.json')
  ];

  let graphPathFound = null;
  for (const p of candidates) {
    if (p && existsSync(p)) {
      graphPathFound = p;
      break;
    }
  }

  if (!graphPathFound) {
    log('info', 'Graphify graph not found in candidate paths — skipping context enrichment');
    return '';
  }

  let graph;
  try {
    graph = JSON.parse(readFileSync(graphPathFound, 'utf8'));
    log('info', `Loaded Graphify context from ${graphPathFound}`);
  } catch (e) {
    log('warn', `Failed to parse Graphify graph at ${graphPathFound}: ${e.message}`);
    return '';
  }

  const nodes = Array.isArray(graph) ? graph : (graph.nodes || graph.files || []);
  const edges = graph.edges || graph.relationships || graph.links || [];
  const repoKey = repoPath.toLowerCase();

  const nodeRepo = (n) => (n.repo || n.repo_path || n.repository || '').toLowerCase();
  const nodePath = (n) => n.path || n.file || n.id || n.name || '';

  // Match nodes belonging to this repo: explicit repo field, or path prefix heuristic
  const matched = nodes.filter(n => {
    const r = nodeRepo(n);
    if (r && (r === repoKey || r.endsWith('/' + repoKey) || r.includes(repoKey))) return true;
    const p = nodePath(n).toLowerCase();
    return !r && (p.startsWith(repoKey + '/') || p.includes('/' + repoKey + '/'));
  });

  if (matched.length === 0) {
    log('info', `Graphify: no nodes matched repo '${repoPath}' — no enrichment applied`);
    return '';
  }

  const matchedIds = new Set(matched.map(n => n.id || nodePath(n)));
  const matchedEdges = edges.filter(e => {
    const s = String(e.source ?? e.from ?? '').toLowerCase();
    const t = String(e.target ?? e.to ?? '').toLowerCase();
    return [...matchedIds].some(id => s.includes(String(id).toLowerCase()) || t.includes(String(id).toLowerCase()));
  });

  const lines = [];
  lines.push('');
  lines.push('## Graphify Codebase Dependency Subgraph');
  lines.push(`Repository: \`${repoPath}\` — ${matched.length} indexed file(s), ${matchedEdges.length} known relationship(s).`);
  lines.push('');
  lines.push('### Indexed Files');
  for (const n of matched.slice(0, 120)) {
    const kind = n.kind || n.type || 'file';
    const lang = n.language || n.lang || '';
    lines.push(`- \`${nodePath(n)}\` (${kind}${lang ? ', ' + lang : ''})`);
  }
  if (matched.length > 120) lines.push(`- ...and ${matched.length - 120} more (truncated)`);

  if (matchedEdges.length > 0) {
    lines.push('');
    lines.push('### AST Relationships');
    for (const e of matchedEdges.slice(0, 150)) {
      const s = e.source ?? e.from;
      const t = e.target ?? e.to;
      const rel = e.type || e.kind || e.relationship || 'depends-on';
      lines.push(`- \`${s}\` —[${rel}]→ \`${t}\``);
    }
    if (matchedEdges.length > 150) lines.push(`- ...and ${matchedEdges.length - 150} more (truncated)`);
  }

  log('info', `Graphify enrichment: ${matched.length} nodes, ${matchedEdges.length} edges for '${repoPath}'`);
  return lines.join('\n');
}

// ==========================================
// Source Resolution
// ==========================================

/** Resolve a repo_path (e.g. "Fabrik8OS") to a Jules source name. */
async function resolveSources() {
  const res = await listSources();
  const sources = res.sources || [];
  const map = new Map(); // lowercase repo name -> { name, defaultBranch }
  for (const s of sources) {
    const repo = s.githubRepo?.repo || s.name.split('/').pop();
    const defaultBranch = s.githubRepo?.defaultBranch?.displayName || 'main';
    if (repo) map.set(repo.toLowerCase(), { name: s.name, defaultBranch });
  }
  return map;
}

// ==========================================
// State Tracking
// ==========================================

/** Fresh v2 state schema. */
function emptyState() {
  return {
    version: STATE_SCHEMA_VERSION,
    sessions: {},
    dispatch: { daily: {}, history: [] },
    prs: {} // PR url -> { status, url, title, repo, sessionId, recordedAt }
  };
}

/** Load state and migrate older schemas forward to v2. */
function loadState() {
  if (!existsSync(STATE_PATH)) return emptyState();
  try {
    const state = JSON.parse(readFileSync(STATE_PATH, 'utf8'));
    if (!state.sessions) state.sessions = {};
    if (!state.dispatch) state.dispatch = { daily: {}, history: [] };
    if (!state.dispatch.daily) state.dispatch.daily = {};
    if (!state.dispatch.history) state.dispatch.history = [];
    if (!state.prs) state.prs = {}; // v1 -> v2 migration
    state.version = STATE_SCHEMA_VERSION;
    return state;
  } catch (e) {
    log('warn', `State file corrupt, starting fresh dispatch ledger: ${e.message}`);
    return emptyState();
  }
}

function saveState(state) {
  // Cap history
  if (state.dispatch.history.length > HISTORY_CAP) {
    state.dispatch.history = state.dispatch.history.slice(-HISTORY_CAP);
  }
  const tmp = STATE_PATH + '.tmp';
  writeFileSync(tmp, JSON.stringify(state, null, 2));
  renameSync(tmp, STATE_PATH);
}

function dailyCount(state) {
  return state.dispatch.daily[chicagoToday()] || 0;
}

// ==========================================
// Daily Digest Module
// ==========================================

/**
 * Compile the daily Jules pipeline digest.
 *
 * Summarizes:
 *   - sessions dispatched today (America/Chicago)
 *   - rate limit status (X / 90 safety ceiling used)
 *   - active Jules PRs awaiting Architect approval
 *   - completed jobs
 *
 * @param {object} [opts]
 * @param {boolean} [opts.send=false] - also push the digest to Discord
 * @returns {Promise<string>} the formatted digest text
 */
export async function generateDailyDigest(opts = {}) {
  const state = loadState();
  const today = chicagoToday();
  const usedToday = state.dispatch.daily[today] || 0;

  // Sessions dispatched today (prefer the recorded Chicago day stamp)
  const todaysDispatches = state.dispatch.history.filter(h =>
    h.day === today || (!h.day && typeof h.dispatchedAt === 'string' && h.dispatchedAt.startsWith(today))
  );

  // PRs awaiting Architect approval (never auto-merged)
  const pendingPrs = Object.values(state.prs || {}).filter(p => p.status === PR_STATUS_AWAITING);

  // Completed jobs tracked in state
  const completedSessions = Object.entries(state.sessions || {})
    .filter(([, s]) => (typeof s === 'object' ? s.state : s) === 'COMPLETED');

  const lines = [];
  lines.push(`📋 **Jules Daily Digest — ${today}**`);
  lines.push(`> **Dispatched today:** ${todaysDispatches.length} session(s)`);
  for (const h of todaysDispatches.slice(-10)) {
    lines.push(`>   • \`${h.repo}\` — ${h.title || h.spec} (\`${h.sessionId}\`)`);
  }
  lines.push(`> **Rate limit:** ${usedToday} / ${DAILY_SAFETY_LIMIT} used (${Math.max(0, DAILY_SAFETY_LIMIT - usedToday)} remaining for auto queue; ${MANUAL_RESERVE_BUFFER} sessions reserved for Ben's manual jobs)`);
  lines.push(`> **PRs awaiting Architect approval:** ${pendingPrs.length}`);
  for (const pr of pendingPrs.slice(0, 15)) {
    lines.push(`>   • [${pr.title || 'Pull Request'}](${pr.url}) — \`${pr.repo}\` (session \`${pr.sessionId}\`)`);
  }
  if (pendingPrs.length > 15) lines.push(`>   • ...and ${pendingPrs.length - 15} more`);
  lines.push(`> **Completed jobs:** ${completedSessions.length}`);
  lines.push(`\n*Auto-merge is disabled. All PRs require Ben's manual review & approval before merging to \`main\`.*`);

  const digest = lines.join('\n');
  console.log(digest);

  // Archive digest to the vault for autonomous Librarian indexing
  try {
    const digestDir = join(WORKSPACE, 'vault/01-ACTIVE/syntheses/jules-digests');
    if (!existsSync(digestDir)) {
      mkdirSync(digestDir, { recursive: true });
    }
    const vaultDigestPath = join(digestDir, `Jules-Daily-Digest-${today}.md`);
    const markdownContent = `# 📋 Jules Daily Digest — ${today}\n\n**Date:** ${today}\n**Generated By:** VANTAGE Jules Queue Pipeline\n\n${digest}\n`;
    writeFileSync(vaultDigestPath, markdownContent, 'utf8');
    log('info', `Saved Daily Digest to vault: ${vaultDigestPath}`);
  } catch (err) {
    log('error', `Failed to write Daily Digest to vault: ${err.message}`);
  }

  if (opts.send) {
    await sendDiscordAlert(digest);
  }
  return digest;
}

// ==========================================
// Main Dispatch Flow
// ==========================================

async function main() {
  // Strict Architect PR Approval Policy — hard circuit breaker, always on.
  assertNoAutoMerge();

  // Digest mode: compile (and optionally broadcast) the daily summary, then exit.
  if (DIGEST_MODE) {
    await generateDailyDigest({ send: DIGEST_SEND && !DRY_RUN });
    return;
  }

  log('info', `Starting queue sweep${DRY_RUN ? ' (DRY RUN)' : ''} — limit: ${RUN_LIMIT === Infinity ? 'none' : RUN_LIMIT}, daily safety cap: ${DAILY_SAFETY_LIMIT}/${DAILY_HARD_LIMIT}`);

  // Ensure queue directories exist
  for (const dir of [QUEUE_DIR, PROCESSED_DIR]) {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
      log('info', `Created missing directory: ${dir}`);
    }
  }

  // Collect pending specs
  const specs = readdirSync(QUEUE_DIR)
    .filter(f => f.endsWith('.md') && statSync(join(QUEUE_DIR, f)).isFile())
    .map(f => {
      const full = join(QUEUE_DIR, f);
      const raw = readFileSync(full, 'utf8');
      const meta = parseSpecMetadata(raw);
      return { file: f, path: full, raw, meta, mtime: statSync(full).mtimeMs };
    })
    .filter(s => {
      if (!s.meta.repo_path) {
        log('warn', `Skipping '${s.file}' — missing required 'repo_path' metadata`);
        return false;
      }
      return true;
    })
    .sort((a, b) => priorityRank(a.meta.priority) - priorityRank(b.meta.priority) || a.mtime - b.mtime);

  if (specs.length === 0) {
    log('info', 'Queue is empty. Nothing to dispatch.');
    return;
  }
  log('info', `Found ${specs.length} pending spec(s): ${specs.map(s => s.file).join(', ')}`);

  // Rate limit check
  const state = loadState();
  const today = chicagoToday();
  let dispatchedToday = dailyCount(state);
  log('info', `Daily dispatch counter (${today}, America/Chicago): ${dispatchedToday}/${DAILY_SAFETY_LIMIT}`);

  if (dispatchedToday >= DAILY_SAFETY_LIMIT) {
    log('warn', `Daily safety limit reached (${dispatchedToday}/${DAILY_SAFETY_LIMIT}). Halting to stay below Google's ${DAILY_HARD_LIMIT}/day hard cap.`);
    return;
  }

  // Resolve Jules sources once
  let sourceMap;
  try {
    sourceMap = await resolveSources();
    log('info', `Resolved ${sourceMap.size} connected Jules source(s)`);
    if (VERBOSE) log('debug', 'Sources:', [...sourceMap.keys()]);
  } catch (e) {
    log('error', `Failed to list Jules sources: ${e.message}`);
    process.exit(1);
  }

  let dispatched = 0;
  for (const spec of specs) {
    if (dispatched >= RUN_LIMIT) {
      log('info', `Run limit reached (--limit ${RUN_LIMIT}). Stopping.`);
      break;
    }
    if (dispatchedToday >= DAILY_SAFETY_LIMIT) {
      log('warn', `Daily safety limit hit mid-run (${dispatchedToday}/${DAILY_SAFETY_LIMIT}). Remaining specs stay queued.`);
      break;
    }

    const { repo_path, title, priority, branch } = spec.meta;
    const sourceObj = sourceMap.get(repo_path.toLowerCase());
    if (!sourceObj) {
      log('error', `No Jules source matches repo_path '${repo_path}' for '${spec.file}' — leaving in queue`);
      continue;
    }

    const source = typeof sourceObj === 'string' ? sourceObj : sourceObj.name;
    const defaultBranch = (typeof sourceObj === 'object' && sourceObj.defaultBranch) ? sourceObj.defaultBranch : 'main';
    const targetBranch = branch || defaultBranch;

    // Build enriched prompt
    let body = stripFrontmatter(spec.raw);
    // Strip local vault references so Jules is not confused by paths outside the Git repo
    body = body
      .replace(/>\s*\*\*Queue Location:\*\*\s*`[^`]+`\r?\n?/gi, '')
      .replace(/Queue Location:\s*vault\/[^\n]+\n?/gi, '')
      .trim();

    const graphBlock = buildGraphifyBlock(repo_path);
    const prompt = `${body}${graphBlock ? '\n\n' + graphBlock : ''}`.trim();
    const sessionTitle = title || basename(spec.file, '.md');

    log('info', `Dispatching '${spec.file}' → ${source} [priority=${priority || 'medium'}]`);
    if (VERBOSE) log('debug', `Prompt preview (first 300 chars): ${prompt.slice(0, 300)}`);

    if (DRY_RUN) {
      log('info', `[DRY RUN] Would create session '${sessionTitle}' on ${source}${graphBlock ? ' with Graphify enrichment' : ''}`);
      dispatched++;
      continue;
    }

    try {
      // AUTO_CREATE_PR opens a PR for review only. Merging is ALWAYS
      // manual (Ben / Architect) — there is no auto-merge code path.
      const session = await createSession(source, prompt, {
        title: sessionTitle,
        startingBranch: targetBranch,
        automationMode: 'AUTO_CREATE_PR',
        requirePlanApproval: false
      });

      const sessionId = (session.name || '').replace('sessions/', '') || session.id || 'unknown';
      dispatched++;
      dispatchedToday++;

      // Update state ledger
      state.dispatch.daily[today] = dispatchedToday;
      state.dispatch.history.push({
        spec: spec.file,
        repo: repo_path,
        source,
        sessionId,
        title: sessionTitle,
        priority: priority || 'medium',
        graphifyEnriched: Boolean(graphBlock),
        day: today,
        dispatchedAt: new Date().toISOString()
      });
      state.sessions[sessionId] = {
        state: 'QUEUED',
        orchestrated: false,
        spec: spec.file,
        repo: repo_path,
        title: sessionTitle,
        prPolicy: PR_STATUS_AWAITING,
        dispatchedAt: new Date().toISOString()
      };
      saveState(state);

      // Move spec to processed/
      const dest = join(PROCESSED_DIR, spec.file);
      renameSync(spec.path, dest);
      log('info', `✅ Session ${sessionId} created for '${spec.file}' → archived to processed/`);

      // Per-job Discord notification (failures must not break the sweep)
      try {
        let alertText = `🚀 **[Jules Job Dispatched]**\n`;
        alertText += `> **Repo:** \`${repo_path}\`\n`;
        alertText += `> **Session:** \`${sessionId}\`\n`;
        alertText += `> **Task:** *${sessionTitle}*\n`;
        alertText += `> **Priority:** \`${priority || 'medium'}\` | **Daily usage:** ${dispatchedToday}/${DAILY_SAFETY_LIMIT}\n`;
        alertText += `*Any PR opened will be held as \`${PR_STATUS_AWAITING}\` — Ben's manual review & approval required before merging.*`;
        await sendDiscordAlert(alertText);
      } catch (notifyErr) {
        log('warn', `Discord dispatch notification failed for '${spec.file}': ${notifyErr.message}`);
      }

      // Gentle pacing between API writes to respect rate limits
      await new Promise(r => setTimeout(r, 1500));
    } catch (e) {
      log('error', `Dispatch failed for '${spec.file}': ${e.message} — leaving in queue`);
    }
  }

  log('info', `Sweep complete. Dispatched: ${dispatched}. Daily total: ${dispatchedToday}/${DAILY_SAFETY_LIMIT}. Remaining in queue: ${specs.length - dispatched}.`);
}

main().catch(e => {
  log('error', `Fatal dispatcher failure: ${e.message}`);
  process.exit(1);
});
